import test from 'node:test';
import assert from 'node:assert/strict';
import {environment} from './game-harness.mjs';
import {viewport} from '../dist/games/shared.js';
import {games} from '../dist/registry.js';
import {expansionGames} from '../dist/games/expansion.js';
import {expansionProfiles} from '../dist/audio/expansion-profiles.js';
import {plantMines,neighbors,revealCells} from '../dist/games/mines.js';
import {scrambleSlide,slideSolved,slideMove} from '../dist/games/slide.js';
import {lightPuzzle,toggleLights} from '../dist/games/lights.js';
import {SHAPES,fitsBlocks,clearBlockLines,rotateBlock} from '../dist/games/blocks.js';
import {dropFour,fourWinner,chooseFour} from '../dist/games/four.js';
import {reversiFlips,reversiMoves,chooseReversi} from '../dist/games/reversi.js';
import {bubbleCluster,floatingBubbles,bubbleNeighbors} from '../dist/games/bubbles.js';
import {bounceGolf} from '../dist/games/golf.js';
import {hoopCrossing} from '../dist/games/hoops.js';
import {segmentDistance} from '../dist/games/slice.js';
import {angleGap} from '../dist/games/orbit.js';
import {makeMaze,mazeNext} from '../dist/games/maze.js';
import {rhythmPattern,rhythmJudgment} from '../dist/games/rhythm.js';

function seed(n=42){return ()=>((n=(n*1664525+1013904223)>>>0)/4294967296);}
function fixed(fn){const old=Math.random;Math.random=()=>.5;try{return fn();}finally{Math.random=old;}}
function instance(id){const env=environment(),meta=games.find(g=>g.id===id),g=meta.create(env.mount,env.api),height=['mines','slide','lights','echo','four','reversi','orbit'].includes(id)?440:480;const f=viewport(390,844,0,0,118,123).field,k=Math.min(f.w/360,f.h/height);const p=(x,y)=>({x:f.x+(f.w-360*k)/2+x*k,y:f.y+(f.h-height*k)/2+y*k});g.start();return {g,env,p,step(seconds){for(let t=0;t<seconds-1e-7;t+=.01)g.tick(Math.min(.01,seconds-t));},score:()=>env.calls.filter(c=>c[0]==='score').at(-1)[1],finish:()=>env.calls.filter(c=>c[0]==='finish')};}
function cellPoint(p,i,cols,x,y,size){return p(x+(i%cols+.5)*size,y+(Math.floor(i/cols)+.5)*size);}

test('exactly 15 distinct additions bring the complete feed to 34',()=>{assert.equal(expansionGames.length,15);assert.equal(games.length,34);assert.equal(new Set(games.map(g=>g.id)).size,34);for(const g of expansionGames){assert.ok(g.instructions.length>80);assert.ok(g.chips.length);assert.equal(games.find(v=>v.id===g.id).audio,expansionProfiles[g.id]);}});
test('all new cues and music have valid, bounded synthesis parameters',()=>{for(const profile of Object.values(expansionProfiles)){assert.equal(profile.music.steps,32);for(const voice of profile.music.voices){assert.equal(voice.notes.length,32);assert.ok(voice.notes.every(n=>n===null||n>=20&&n<=100));}for(const notes of Object.values(profile.sounds))for(const n of notes){assert.ok(n.duration>0&&n.duration<1);assert.ok(n.gain>0&&n.gain<=.3);assert.ok(n.note>=20&&n.note<=100);}}});
test('Minesweeper always protects first click and neighbors, at every position',()=>{for(let first=0;first<49;first++){const mines=plantMines(first,seed(first+1));assert.equal(mines.size,8);for(const n of [first,...neighbors(first)])assert.ok(!mines.has(n));const board=Array(49).fill(0);const opened=revealCells(board,mines,first);assert.ok(opened.length>=4);assert.ok(opened.every(i=>!mines.has(i)));}});
test('Minesweeper flags resist flood fill and all safe squares finish the game',()=>fixed(()=>{const board=Array(49).fill(0);board[1]=2;revealCells(board,new Set([48]),0);assert.equal(board[1],2);const {g,p,score,finish}=instance('mines'),mines=plantMines(24);g.tap(cellPoint(p,24,7,19,44,46));for(let i=0;i<49;i++)if(!mines.has(i))g.tap(cellPoint(p,i,7,19,44,46));assert.equal(score(),41);assert.equal(finish().length,1);assert.equal(finish()[0][4],'win');g.destroy();}));
test('sliding boards are nontrivial and solvable; nonadjacent moves do nothing',()=>{for(let n=0;n<100;n++){const b=scrambleSlide(seed(n+1));assert.equal(new Set(b).size,9);assert.ok(!slideSolved(b));const a=b.filter(Boolean);let inversions=0;for(let i=0;i<a.length;i++)for(let j=i+1;j<a.length;j++)if(a[i]>a[j])inversions++;assert.equal(inversions%2,0);}const b=[1,2,3,4,5,6,7,8,0];assert.equal(slideMove(b,0),false);assert.equal(slideMove(b,7),true);assert.equal(slideMove(b,8),true);assert.ok(slideSolved(b));});
function solveLights(b){for(let mask=1;mask<65536;mask++){const copy=[...b];for(let i=0;i<16;i++)if(mask&(1<<i))toggleLights(copy,i);if(!copy.some(Boolean))return Array.from({length:16},(_,i)=>i).filter(i=>mask&(1<<i));}throw Error('Unsolvable lights');}
test('all five Lights Out circuits can be completed through actual input',()=>fixed(()=>{const {g,p,step,finish,score}=instance('lights');for(let level=1;level<=5;level++){const solution=solveLights(lightPuzzle(level));for(const i of solution)g.tap(cellPoint(p,i,4,20,52,80));if(level<5)step(1.1);}assert.equal(finish().length,1);assert.equal(finish()[0][4],'win');assert.ok(score()>=250);g.destroy();}));
test('Echo ignores input during playback, accepts a pattern, and rejects a wrong note',()=>fixed(()=>{const {g,step,score,finish}=instance('echo');g.direction('left');assert.equal(score(),0);step(3.1);for(let i=0;i<3;i++)g.direction('left');assert.equal(score(),1);step(5);g.direction('up');assert.equal(finish().length,1);g.destroy();}));
test('block rotations, boundary collision and simultaneous four-line clears',()=>{const b=Array.from({length:16},()=>Array(10).fill(0));assert.equal(fitsBlocks(b,SHAPES[0],-1,0),false);assert.equal(fitsBlocks(b,SHAPES[0],6,0),true);for(let r=12;r<16;r++)b[r].fill(1);const result=clearBlockLines(b);assert.equal(result.count,4);assert.equal(result.board.length,16);assert.ok(result.board.flat().every(n=>n===0));let shape=SHAPES[2];for(let i=0;i<4;i++)shape=rotateBlock(shape);assert.deepEqual(shape,SHAPES[2]);});
test('Pocket Blocks hard drops lock pieces and top-out ends only once',()=>{const {g,finish}=instance('blocks');for(let n=0;n<100;n++)g.action();assert.equal(finish().length,1);g.start();assert.equal(finish().length,1);g.destroy();});
test('Four in a Row detects all line directions and CPU wins or blocks',()=>{for(const cells of [[35,36,37,38],[0,7,14,21],[0,8,16,24],[6,12,18,24]]){const b=Array(42).fill(0);cells.forEach(i=>b[i]=1);assert.equal(fourWinner(b).who,1);}for(const who of [1,2]){const b=Array(42).fill(0);[0,1,2].forEach(col=>dropFour(b,col,who));assert.equal(chooseFour(b),3);}});
test('Reversi flips only bracketed discs and CPU always chooses a legal move',()=>{const b=Array(36).fill(0);b[14]=b[21]=2;b[15]=b[20]=1;assert.deepEqual(reversiMoves(b,1),[8,13,22,27]);assert.deepEqual(reversiFlips(b,8,1),[14]);assert.ok(reversiMoves(b,2).includes(chooseReversi(b)));assert.deepEqual(reversiFlips(b,14,1),[]);const edge=Array(36).fill(0);edge[4]=1;edge[5]=2;assert.deepEqual(reversiFlips(edge,6,1),[]);});
test('bubble matches follow hex neighbors and only unanchored clusters fall',()=>{const b=Array.from({length:10},()=>Array(8).fill(0));b[0][0]=b[1][0]=b[1][1]=1;b[2][5]=b[3][5]=2;assert.equal(bubbleCluster(b,0,0).length,3);assert.deepEqual(floatingBubbles(b),[[2,5],[3,5]]);for(let r=0;r<10;r++)for(let col=0;col<8;col++)for(const [rr,cc] of bubbleNeighbors(r,col))assert.ok(bubbleNeighbors(rr,cc).some(([y,x])=>y===r&&x===col));});
test('golf walls reflect an incoming ball and retain a finite position',()=>{const b={x:100,y:96,vx:10,vy:200};assert.equal(bounceGolf(b,[70,100,100,15]),true);assert.ok(b.vy<0);assert.equal(b.y,93);assert.ok(Number.isFinite(b.vx));});
test('first golf hole can actually be sunk with a controlled putt',()=>{const {g,step,score,env}=instance('golf');for(let n=0;n<3;n++)g.direction('up');g.action();step(5);assert.ok(score()>0);assert.ok(env.calls.some(c=>c[0]==='sound'&&c[1]==='cup'));g.destroy();});
test('hoops only awards descending shots through the inside of the rim',()=>{assert.ok(hoopCrossing({x:180,y:150},{x:180,y:180,vy:200},180));assert.ok(!hoopCrossing({x:180,y:190},{x:180,y:150,vy:-200},180));assert.ok(!hoopCrossing({x:211,y:150},{x:211,y:180,vy:200},180));});
test('Swish default keyboard shot scores once and the tenth attempt ends the round',()=>{const {g,step,score,finish}=instance('hoops');g.action();step(3);assert.ok(score()>=10);const first=score();step(2);assert.equal(score(),first);for(let i=0;i<9;i++){g.action();step(3);}assert.equal(finish().length,1);g.destroy();});
test('Lane Rush can survive all 60 seconds by taking each open lane',()=>fixed(()=>{const {g,step,finish,score}=instance('sprint');step(60.1);assert.equal(finish().length,1);assert.equal(finish()[0][4],'win');assert.ok(score()>500);g.destroy();}));
test('slicing detects swept intersections, including zero-length taps',()=>{assert.equal(segmentDistance({x:50,y:0},{x:0,y:0},{x:100,y:0}),0);assert.equal(segmentDistance({x:50,y:20},{x:0,y:0},{x:100,y:0}),20);assert.equal(segmentDistance({x:3,y:4},{x:0,y:0},{x:0,y:0}),5);});
test('Prism Slice rewards a real sweep through a wave and ignores a second cut',()=>fixed(()=>{const {g,p,step,score}=instance('slice');step(1.4);g.pointerDown(p(90,239));g.pointerMove(p(260,239));g.pointerUp(p(260,239));assert.ok(score()>=20);const before=score();g.pointerDown(p(90,239));g.pointerMove(p(260,239));g.pointerUp(p(260,239));assert.equal(score(),before);g.destroy();}));
test('orbit wraps angles correctly and timing hits score while spamming misses ends',()=>{assert.ok(angleGap(.01,Math.PI*2-.01)<.021);const {g,step,score,finish}=instance('orbit');step((.3+Math.PI/2)/1.5);g.action();assert.equal(score(),20);g.action();g.action();g.action();assert.equal(finish().length,1);g.destroy();});
test('every generated maze is fully connected with reciprocal walls and a path to exit',()=>{for(let n=0;n<40;n++){const maze=makeMaze(seed(n+1)),seen=new Set([0]),todo=[0];while(todo.length){const i=todo.pop();for(const [d,op] of [['up','down'],['right','left'],['down','up'],['left','right']]){const next=mazeNext(maze,i,d);assert.ok(next>=0&&next<63);if(next!==i)assert.equal(mazeNext(maze,next,op),i);if(!seen.has(next)){seen.add(next);todo.push(next);}}}assert.equal(seen.size,63);}});
test('Beat Drop perfect input can finish all 64 beats; hit spam cannot double score',()=>{const {g,step,score,finish}=instance('rhythm');let now=0;for(let i=0;i<64;i++){const time=i<32?2+i*.48:2+32*.48+(i-32)*.42;step(time-now);now=time;g.direction(['left','up','down','right'][rhythmPattern[i%32]]);const before=score();g.direction(['left','up','down','right'][rhythmPattern[i%32]]);assert.equal(score(),before);}step(.6);assert.equal(finish().length,1);assert.equal(finish()[0][4],'win');assert.ok(score()>6400);assert.equal(rhythmJudgment(.084),'perfect');assert.equal(rhythmJudgment(.18),'good');assert.equal(rhythmJudgment(.2),null);g.destroy();});
test('every new game freezes at dt=0, restarts, and becomes inert after destroy',()=>{for(const meta of expansionGames){const {g,env,step,score}=instance(meta.id);step(.2);g.cancel?.();const before=score();for(let n=0;n<100;n++)g.tick(0);assert.equal(score(),before,meta.id);g.start();assert.equal(score(),0,meta.id);g.destroy();const count=env.calls.length;g.action?.();g.direction?.('left');g.tap?.({x:180,y:220});g.tick(.03);assert.equal(env.calls.length,count,`${meta.id} still active after destroy`);env.checkCleanup();}});

test('Bubble Sky a matching shot clears a connected ceiling and wins once',()=>fixed(()=>{const {g,step,finish,score}=instance('bubbles');g.action();step(2);assert.equal(score(),330);assert.equal(finish().length,1);assert.equal(finish()[0][4],'win');g.destroy();}));
test('all five golf courses have a playable route within the stroke budget',()=>{const {g,p,step,finish,score}=instance('golf');const routes=[[[180,386],[180,90]],[[80,386],[280,310],[275,88]],[[280,385],[78,285],[72,94]],[[180,390],[300,310],[300,135],[180,85]],[[65,385],[280,315],[280,210],[90,210],[90,95],[292,89]]];for(const route of routes)for(let i=1;i<route.length;i++){const dx=route[i][0]-route[i-1][0],dy=route[i][1]-route[i-1][1],dist=Math.hypot(dx,dy),power=Math.min(480,dist*1.15+9);g.pointerDown(p(180,250));g.pointerMove(p(180-dx/dist*power/4,250-dy/dist*power/4));g.pointerUp(p(180-dx/dist*power/4,250-dy/dist*power/4));step(5);}assert.equal(finish().length,1);assert.equal(finish()[0][4],'win');assert.ok(score()>500);g.destroy();});
test('three full Maze Escape rounds can collect all sparks and reach the exit',()=>fixed(()=>{const {g,step,finish,score}=instance('maze'),maze=makeMaze();for(let level=0;level<3;level++){const seen=new Set();function walk(i){seen.add(i);for(const d of ['up','right','down','left']){const next=mazeNext(maze,i,d);if(next===i||seen.has(next))continue;g.direction(d);walk(next);g.direction({up:'down',right:'left',down:'up',left:'right'}[d]);}}
  // Visit every cell, then find a shortest route to the exit. Completion may
  // occur during the traversal; transition remains deliberately clock-gated.
  walk(0);const todo=[[0,[]]],visited=new Set([0]);let path=[];while(todo.length){const [i,ds]=todo.shift();if(i===62){path=ds;break;}for(const d of ['up','right','down','left']){const n=mazeNext(maze,i,d);if(!visited.has(n)){visited.add(n);todo.push([n,[...ds,d]]);}}}for(const d of path)g.direction(d);if(level<2)step(1);
 }assert.equal(finish().length,1);assert.equal(finish()[0][4],'win');assert.ok(score()>=525);g.destroy();}));
